"""Initial migration

Revision ID: 33cae8e26def
Revises: 
Create Date: 2024-08-20 16:46:44.411074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33cae8e26def'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('gold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('usernameid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usernameid'], ['users.id'], name=op.f('fk_gold_usernameid_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pickaxe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('usernameid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usernameid'], ['users.id'], name=op.f('fk_pickaxe_usernameid_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pickaxe')
    op.drop_table('gold')
    op.drop_table('users')
    # ### end Alembic commands ###
