DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE gold (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  amount INTEGER NOT NULL
);

CREATE TABLE pickaxe(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  strength INTEGER NOT NULL
);